<script lang="ts">
	const lastUpdated = new Date().toLocaleDateString('en-US', {
		month: 'long',
		day: 'numeric',
		year: 'numeric'
	});
</script>

<svelte:head>
	<title>Zero-Knowledge Encryption — filez.zone</title>
	<meta
		name="description"
		content="Learn how filez.zone uses zero-knowledge encryption to ensure your files can never be read by anyone but the recipient. Encryption happens in your browser — keys never touch our servers."
	/>
	<meta name="robots" content="index, follow" />
	<meta property="og:title" content="Zero-Knowledge Encryption — filez.zone" />
	<meta
		property="og:description"
		content="Zero-knowledge architecture ensures filez.zone can never read your files. Client-side AES-256-GCM encryption, keys in the URL hash fragment, and burn-after-reading deletion."
	/>
	<meta property="og:url" content="https://filez.zone/zero-knowledge" />
	<meta property="og:type" content="website" />
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="Zero-Knowledge Encryption — filez.zone" />
	<meta
		name="twitter:description"
		content="Learn how zero-knowledge encryption protects your files on filez.zone. Keys never leave your browser."
	/>
	<link rel="canonical" href="https://filez.zone/zero-knowledge" />
</svelte:head>

<div class="w-full max-w-2xl">
	<div
		class="bg-white rounded-2xl shadow-lg shadow-slate-200/50 border border-slate-100 p-8 sm:p-10"
	>
		<h1 class="text-2xl font-semibold text-slate-800 mb-1">Zero-Knowledge Encryption</h1>
		<p class="text-sm text-slate-400 mb-8">Last updated: {lastUpdated}</p>

		<div class="prose prose-slate prose-sm max-w-none space-y-6 text-slate-600 leading-relaxed">
			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">What is Zero Knowledge?</h2>
				<p>
					<strong>Zero knowledge</strong> means that the service provider — filez.zone — has
					<strong>zero knowledge</strong> of your file contents. We designed our entire system so
					that the server never sees the plaintext data you upload, never possesses the encryption
					keys, and never has the ability to decrypt your files. Even if our servers were
					compromised, your data remains unreadable.
				</p>
				<p class="mt-2">
					This is not a marketing claim — it's enforced by cryptography and architecture. The
					encryption key is generated in your browser, used only in your browser, and embedded in
					a shareable link in a way that browsers never transmit to web servers. We simply store
					and serve opaque encrypted blobs we cannot read.
				</p>
			</section>

			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">How It Works</h2>

				<!-- Step 1 -->
				<div class="flex gap-4 mt-4">
					<div
						class="shrink-0 w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center text-sm font-bold"
					>
						1
					</div>
					<div>
						<h3 class="text-sm font-semibold text-slate-700">Key generation in your browser</h3>
						<p class="mt-1">
							When you pick a file to share, a unique 256-bit AES-GCM key is generated
							directly in your browser using the
							<a
								href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API"
								class="text-blue-500 hover:text-blue-600 underline"
								target="_blank"
								rel="noopener">Web Crypto API</a
							>. This key never leaves your device in plaintext. A random file identifier
							(UUID) is also generated to reference the upload.
						</p>
					</div>
				</div>

				<!-- Step 2 -->
				<div class="flex gap-4 mt-5">
					<div
						class="shrink-0 w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center text-sm font-bold"
					>
						2
					</div>
					<div>
						<h3 class="text-sm font-semibold text-slate-700">Client-side encryption</h3>
						<p class="mt-1">
							The file is split into 5 MB chunks. Each chunk is encrypted with AES-256-GCM
							using a random 12-byte initialization vector (IV) per chunk. The output for
							each chunk is: <code class="bg-slate-100 px-1 py-0.5 rounded text-xs">IV (12 bytes) || ciphertext || GCM tag (16 bytes)</code>.
							All encryption happens locally — the original file never leaves your browser.
						</p>
					</div>
				</div>

				<!-- Step 3 -->
				<div class="flex gap-4 mt-5">
					<div
						class="shrink-0 w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center text-sm font-bold"
					>
						3
					</div>
					<div>
						<h3 class="text-sm font-semibold text-slate-700">Direct upload to storage</h3>
						<p class="mt-1">
							Each encrypted chunk is uploaded directly to Cloudflare R2 via presigned URLs
							generated by our backend. Critically, the file data <strong>never passes through
							our backend servers</strong> — it travels straight from your browser to R2. The
							backend only coordinates the multipart upload flow. It sees upload IDs and part
							numbers, but never the actual bytes, plaintext or ciphertext.
						</p>
					</div>
				</div>

				<!-- Step 4 -->
				<div class="flex gap-4 mt-5">
					<div
						class="shrink-0 w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center text-sm font-bold"
					>
						4
					</div>
					<div>
						<h3 class="text-sm font-semibold text-slate-700">
							Key embedded in the URL hash fragment
						</h3>
						<p class="mt-1">
							The encryption key is encoded as URL-safe base64 and appended to the
							shareable link after a <code class="bg-slate-100 px-1 py-0.5 rounded text-xs">#</code>
							(hash). For example:
							<code class="bg-slate-100 px-1 py-0.5 rounded text-xs break-all">/f/uuid#base64key</code>.
							Hash fragments are <strong>never transmitted in HTTP requests</strong> — this is a
							fundamental browser security property. When someone opens the link, the key is
							extracted locally by JavaScript in their browser. The server never sees it.
						</p>
					</div>
				</div>

				<!-- Step 5 -->
				<div class="flex gap-4 mt-5">
					<div
						class="shrink-0 w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center text-sm font-bold"
					>
						5
					</div>
					<div>
						<h3 class="text-sm font-semibold text-slate-700">
							Download, decrypt, and burn after reading
						</h3>
						<p class="mt-1">
							When a recipient opens the link, their browser requests the encrypted blob
							from our backend. The backend fetches it from R2, streams it back, and
							<strong>immediately deletes the object from storage</strong>. The recipient's
							browser then decrypts each chunk using the key from the hash fragment and
							reassembles the original file. After this single download, the file no longer
							exists on our infrastructure — burn after reading.
						</p>
					</div>
				</div>
			</section>

			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">What the Server Can See</h2>
				<p>It's important to be transparent. While we cannot read your file contents, our infrastructure does process some metadata:</p>

				<div class="overflow-x-auto mt-2">
					<table class="w-full text-left text-xs border-collapse">
						<thead>
							<tr class="border-b border-slate-200">
								<th class="py-2 pr-4 font-semibold text-slate-700">Data</th>
								<th class="py-2 pr-4 font-semibold text-slate-700">Visible to server?</th>
								<th class="py-2 font-semibold text-slate-700">Explanation</th>
							</tr>
						</thead>
						<tbody>
							<tr class="border-b border-slate-100">
								<td class="py-2 pr-4 font-medium">File contents</td>
								<td class="py-2 pr-4">
									<span class="inline-flex items-center gap-1 text-red-600 font-medium">
										<svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
										No
									</span>
								</td>
								<td class="py-2">Stored and served as opaque ciphertext. No plaintext access.</td>
							</tr>
							<tr class="border-b border-slate-100">
								<td class="py-2 pr-4 font-medium">Encryption key</td>
								<td class="py-2 pr-4">
									<span class="inline-flex items-center gap-1 text-red-600 font-medium">
										<svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
										No
									</span>
								</td>
								<td class="py-2">Lives in URL hash fragment — never sent in HTTP requests.</td>
							</tr>
							<tr class="border-b border-slate-100">
								<td class="py-2 pr-4 font-medium">Original file name</td>
								<td class="py-2 pr-4">
									<span class="inline-flex items-center gap-1 text-red-600 font-medium">
										<svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/></svg>
										No
									</span>
								</td>
								<td class="py-2">Not transmitted to the backend.</td>
							</tr>
							<tr class="border-b border-slate-100">
								<td class="py-2 pr-4 font-medium">File ID (UUID)</td>
								<td class="py-2 pr-4">
									<span class="inline-flex items-center gap-1 text-amber-600 font-medium">~</span>
								</td>
								<td class="py-2">Generated client-side, used as the storage key. Random, reveals nothing.</td>
							</tr>
							<tr class="border-b border-slate-100">
								<td class="py-2 pr-4 font-medium">Content type (MIME)</td>
								<td class="py-2 pr-4">
									<span class="inline-flex items-center gap-1 text-green-600 font-medium">
										<svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
										Yes
									</span>
								</td>
								<td class="py-2">Optional metadata (e.g. "image/png") to help the recipient. Stored alongside the ciphertext.</td>
							</tr>
							<tr class="border-b border-slate-100">
								<td class="py-2 pr-4 font-medium">Upload timestamp & size</td>
								<td class="py-2 pr-4">
									<span class="inline-flex items-center gap-1 text-green-600 font-medium">
										<svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
										Yes
									</span>
								</td>
								<td class="py-2">Standard S3 object metadata. Encrypted file size only (slightly larger than original).</td>
							</tr>
							<tr class="border-b border-slate-100">
								<td class="py-2 pr-4 font-medium">IP address</td>
								<td class="py-2 pr-4">
									<span class="inline-flex items-center gap-1 text-green-600 font-medium">
										<svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
										Yes
									</span>
								</td>
								<td class="py-2">Logged temporarily for rate limiting and abuse prevention. Not linked to file content.</td>
							</tr>
						</tbody>
					</table>
				</div>
				<p class="mt-3 text-xs text-slate-500">
					The key takeaway: everything that could identify or reveal your file's content is either
					never sent to us (key, file name, plaintext) or encrypted beyond our reach (file contents).
				</p>
			</section>

			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">Why the Hash Fragment Matters</h2>
				<p>
					The URL hash fragment (the part after <code class="bg-slate-100 px-1 py-0.5 rounded text-xs">#</code>)
					is special in HTTP: browsers <strong>never include it in HTTP requests</strong>. This is
					not something we enforce — it's a fundamental rule of how the web works. When you type a
					URL with a hash into your browser, or when someone clicks a link with a hash, the
					fragment stays in the browser's address bar and is accessible to JavaScript, but it is
					never sent over the network in any HTTP request.
				</p>
				<p class="mt-2">
					This means the encryption key — which we embed in the hash fragment — is physically
					impossible for our servers to receive, even if we wanted to. The key exchange happens
					entirely between the sender and the recipient, mediated only by the URL they share
					through any channel they choose (messenger, email, QR code, etc.).
				</p>
				<div class="mt-3 p-3 bg-slate-50 border border-slate-200 rounded-lg">
					<p class="text-xs text-slate-600">
						<strong>Example capability URL:</strong><br />
						<code class="text-xs break-all">https://filez.zone/f/a1b2c3d4-e5f6-7890-abcd-ef1234567890#dGhpcyBpcyBhIGtleQ</code>
					</p>
					<p class="text-xs text-slate-500 mt-1.5">
						The browser sends <code class="bg-slate-100 px-1 py-0.5 rounded text-xs">GET /f/a1b2c3d4-...</code>
						to the server. The part after <code class="bg-slate-100 px-1 py-0.5 rounded text-xs">#</code> is
						never transmitted. JavaScript extracts it locally to decrypt the file.
					</p>
				</div>
			</section>

			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">End-to-End vs. Zero Knowledge</h2>
				<p>
					These terms are related but distinct:
				</p>
				<ul class="list-disc pl-5 mt-2 space-y-2">
					<li>
						<strong>End-to-end encryption (E2EE)</strong> means data is encrypted on the
						sender's device and can only be decrypted on the recipient's device. No
						intermediary can read it in transit. filez.zone implements this: only the
						sender and recipient ever hold the key.
					</li>
					<li>
						<strong>Zero knowledge</strong> goes a step further: it means the service
						provider has no technical ability to access the plaintext, even if compelled.
						This is achieved because we never possess the key at any point — it's generated
						locally, transmitted only through the hash fragment, and used only in the
						browser.
					</li>
				</ul>
				<p class="mt-2">
					filez.zone is both end-to-end encrypted <em>and</em> zero-knowledge. We cannot
					decrypt your files even if we wanted to or were legally required to.
				</p>
			</section>

			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">What This Protects Against</h2>
				<div class="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
					<div class="p-3 bg-green-50 border border-green-200 rounded-lg">
						<h3 class="text-xs font-semibold text-green-800">✓ Server breaches</h3>
						<p class="text-xs text-green-700 mt-1">
							A compromised server yields only encrypted blobs — no keys, no plaintext.
						</p>
					</div>
					<div class="p-3 bg-green-50 border border-green-200 rounded-lg">
						<h3 class="text-xs font-semibold text-green-800">✓ Man-in-the-middle attacks</h3>
						<p class="text-xs text-green-700 mt-1">
							Keys travel in hash fragments, not over the network. HTTPS protects the ciphertext.
						</p>
					</div>
					<div class="p-3 bg-green-50 border border-green-200 rounded-lg">
						<h3 class="text-xs font-semibold text-green-800">✓ Subpoenas & legal requests</h3>
						<p class="text-xs text-green-700 mt-1">
							We have nothing to hand over — we don't have the keys or plaintext.
						</p>
					</div>
					<div class="p-3 bg-green-50 border border-green-200 rounded-lg">
						<h3 class="text-xs font-semibold text-green-800">✓ Insider threats</h3>
						<p class="text-xs text-green-700 mt-1">
							No employee or administrator can access your files. It's cryptographically impossible.
						</p>
					</div>
					<div class="p-3 bg-green-50 border border-green-200 rounded-lg">
						<h3 class="text-xs font-semibold text-green-800">✓ Cloud provider access</h3>
						<p class="text-xs text-green-700 mt-1">
							Cloudflare R2 stores encrypted data only — they cannot decrypt it.
						</p>
					</div>
					<div class="p-3 bg-green-50 border border-green-200 rounded-lg">
						<h3 class="text-xs font-semibold text-green-800">✓ Accidental leaks</h3>
						<p class="text-xs text-green-700 mt-1">
							Files auto-delete after first download. Nothing lingers to be exposed later.
						</p>
					</div>
				</div>
			</section>

			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">Limitations &amp; Responsibilities</h2>
				<p>
					Zero knowledge protects your data from us, but it cannot protect against everything.
					You are responsible for:
				</p>
				<ul class="list-disc pl-5 mt-2 space-y-1.5">
					<li>
						<strong>Sharing the link securely.</strong> Anyone with the capability URL can
						download the file once. If you share it over an insecure channel and it's
						intercepted, the interceptor can access the file before the intended
						recipient.
					</li>
					<li>
						<strong>Verifying the recipient.</strong> The burn-after-read model means the
						first person to open the link gets the file. Make sure you're sharing with the
						right person.
					</li>
					<li>
						<strong>Your own device security.</strong> The encryption key is generated and
						used in your browser. If your device is compromised (malware, keyloggers,
						browser extensions), the key could be intercepted before it's embedded in the
						hash fragment.
					</li>
				</ul>
				<p class="mt-2">
					These are inherent trade-offs in any zero-knowledge system where the service
					provider is intentionally kept out of the trust boundary. We believe this is the
					right trade-off: you control the data, and with that comes the responsibility to
					handle the link with care.
				</p>
			</section>

			<section>
				<h2 class="text-base font-semibold text-slate-800 mb-2">Technical Verification</h2>
				<p>
					You don't have to take our word for it. filez.zone is
					<a
						href="https://github.com/ttstt/file-sharing"
						class="text-blue-500 hover:text-blue-600 underline"
						target="_blank"
						rel="noopener">open source</a
					>. You can inspect the encryption logic in
					<code class="bg-slate-100 px-1 py-0.5 rounded text-xs">frontend/src/lib/crypto.ts</code>,
					the upload flow in
					<code class="bg-slate-100 px-1 py-0.5 rounded text-xs">frontend/src/lib/upload.ts</code>,
					and the backend handlers that confirm files are stored and served as opaque binary
					streams without any decryption capability. The entire codebase is publicly available
					on GitHub.
				</p>
				<p class="mt-2">
					You can also verify the behavior directly in your browser's developer tools:
				</p>
				<ul class="list-disc pl-5 mt-2 space-y-1.5">
					<li>
						Open the <strong>Network tab</strong> during upload — you'll see encrypted
						chunks being PUT directly to R2, never POSTed to our backend.
					</li>
					<li>
						Inspect the capability URL — the key is in the hash fragment, and the
						<strong>only HTTP request</strong> made during download is a GET to the
						backend with the file ID (no key in the request).
					</li>
					<li>
						Check the <strong>Sources tab</strong> for the unminified client-side
						code — all cryptographic operations are visible and auditable.
					</li>
				</ul>
			</section>
		</div>
	</div>

	<p class="text-center text-xs text-slate-400 mt-6">
		<a href="/" class="text-blue-500 hover:text-blue-600 transition-colors">← Back to filez.zone</a>
	</p>
</div>
